/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThesesIndexRouteImport } from './routes/theses.index'
import { Route as ConceptsIndexRouteImport } from './routes/concepts.index'
import { Route as AdvisorsIndexRouteImport } from './routes/advisors.index'
import { Route as ThesesSlugRouteImport } from './routes/theses.$slug'
import { Route as ConceptsSlugRouteImport } from './routes/concepts.$slug'
import { Route as AdvisorsSlugRouteImport } from './routes/advisors.$slug'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesesIndexRoute = ThesesIndexRouteImport.update({
  id: '/theses/',
  path: '/theses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsIndexRoute = AdvisorsIndexRouteImport.update({
  id: '/advisors/',
  path: '/advisors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesesSlugRoute = ThesesSlugRouteImport.update({
  id: '/theses/$slug',
  path: '/theses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/concepts/$slug',
  path: '/concepts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsSlugRoute = AdvisorsSlugRouteImport.update({
  id: '/advisors/$slug',
  path: '/advisors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/advisors/$slug': typeof AdvisorsSlugRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/theses/$slug': typeof ThesesSlugRoute
  '/advisors/': typeof AdvisorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/theses/': typeof ThesesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/advisors/$slug': typeof AdvisorsSlugRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/theses/$slug': typeof ThesesSlugRoute
  '/advisors': typeof AdvisorsIndexRoute
  '/concepts': typeof ConceptsIndexRoute
  '/theses': typeof ThesesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/advisors/$slug': typeof AdvisorsSlugRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/theses/$slug': typeof ThesesSlugRoute
  '/advisors/': typeof AdvisorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/theses/': typeof ThesesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/graph'
    | '/timeline'
    | '/trends'
    | '/advisors/$slug'
    | '/concepts/$slug'
    | '/theses/$slug'
    | '/advisors/'
    | '/concepts/'
    | '/theses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/graph'
    | '/timeline'
    | '/trends'
    | '/advisors/$slug'
    | '/concepts/$slug'
    | '/theses/$slug'
    | '/advisors'
    | '/concepts'
    | '/theses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/graph'
    | '/timeline'
    | '/trends'
    | '/advisors/$slug'
    | '/concepts/$slug'
    | '/theses/$slug'
    | '/advisors/'
    | '/concepts/'
    | '/theses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GraphRoute: typeof GraphRoute
  TimelineRoute: typeof TimelineRoute
  TrendsRoute: typeof TrendsRoute
  AdvisorsSlugRoute: typeof AdvisorsSlugRoute
  ConceptsSlugRoute: typeof ConceptsSlugRoute
  ThesesSlugRoute: typeof ThesesSlugRoute
  AdvisorsIndexRoute: typeof AdvisorsIndexRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
  ThesesIndexRoute: typeof ThesesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theses/': {
      id: '/theses/'
      path: '/theses'
      fullPath: '/theses/'
      preLoaderRoute: typeof ThesesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts/'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors/': {
      id: '/advisors/'
      path: '/advisors'
      fullPath: '/advisors/'
      preLoaderRoute: typeof AdvisorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theses/$slug': {
      id: '/theses/$slug'
      path: '/theses/$slug'
      fullPath: '/theses/$slug'
      preLoaderRoute: typeof ThesesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/concepts/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors/$slug': {
      id: '/advisors/$slug'
      path: '/advisors/$slug'
      fullPath: '/advisors/$slug'
      preLoaderRoute: typeof AdvisorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GraphRoute: GraphRoute,
  TimelineRoute: TimelineRoute,
  TrendsRoute: TrendsRoute,
  AdvisorsSlugRoute: AdvisorsSlugRoute,
  ConceptsSlugRoute: ConceptsSlugRoute,
  ThesesSlugRoute: ThesesSlugRoute,
  AdvisorsIndexRoute: AdvisorsIndexRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
  ThesesIndexRoute: ThesesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
